# Generated by Django 3.1 on 2020-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='skill',
            name='rank',
            field=models.IntegerField(default=99),
        ),
    ]
