# Generated by Django 3.1 on 2020-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200812_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_fab_icon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_fab_icon',
            field=models.BooleanField(default=True),
        ),
    ]
