# Generated by Django 3.1 on 2020-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='show_as_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
