# Generated by Django 3.1 on 2021-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_quote_show_as_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
