# Generated by Django 3.1 on 2021-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
